name: Release Governance

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - name: Run Release Please
        id: release
        uses: googleapis/release-please-action@7987452d334254bdc0230f40a1b64ff13550b719 # v4.1.4
        with:
          release-type: node
          package-name: root-application
